version: 0.2
phases:
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
      - mvn clean test -Dsuites=ui -Denv.file=sit -Dselenide.remote=http://3.141.167.95:4444/wd/hub

